### ISSUE TITLE
Horizontal init wrong _harvesterCount

### ISSUE THREAD

**Issue by bunbogionac** [aavegotchi/aavegotchi-realm-diamond#97]
https://github.com/aavegotchi/aavegotchi-realm-diamond/commit/1fdbfe8b9a302ead72d8d0715d221de48b849d67
![image](https://user-images.githubusercontent.com/90376623/180734483-399cbddd-142e-4201-875a-4338432cb7fc.png)
![image](https://user-images.githubusercontent.com/90376623/180734498-0761ab0b-e50f-48a8-a961-1c055eaeb221.png)
index 3 -> 4 for paartner parcel

**Comment by cinnabarhorse** [comment]
Fixed, thank you!
